### ISSUE TITLE
Build fails with javadoc error on JDK 1.7

### ISSUE THREAD

**Issue by oarchner** [dataArtisans/flink-training-exercises#16]
mvn clean install fails on JDK 1.7 with:  javadoc: error - invalid flag: -Xdoclint:none 
Seems that you used an invalid javadoc option for JDK 1.7 in your pom.xml on line 200.

**Comment by a6822342** [comment]
I have this problem too.but i use this command:mvn -Dmaven.skip=ture verify.I dont know is this right,Can anybody help me?

**Comment by StephanEwen** [comment]
You can temporarily circumvent this by doing `mvn clean install -Dmaven.javadoc.skip=true`

**Comment by StephanEwen** [comment]
The project seems to not be set up for Java 7. Because Java broke the JavaDoc tool behavior between Java 7 and Java 8, this needs the following changes:

  1. Remove the `<additionalparam>-Xdoclint:none</additionalparam>` from the javadoc section.

  2. Add a Java 8 profile that activates that parameter only when Java 8 is used:
```
		<profile>
			<id>jdk8</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<jdk>1.8</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>2.9.1</version>
						<configuration>
							<quiet>true</quiet>
						</configuration>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<goals>
									<goal>jar</goal>
								</goals>
								<configuration>
									<additionalparam>-Xdoclint:none</additionalparam>
									<detectOfflineLinks>false</detectOfflineLinks>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
```

**Comment by a6822342** [comment]
mvn clean install -Dmaven.javadoc.skip=true.

**Comment by a6822342** [comment]
mvn clean install -Dmaven.javadoc.skip=true         this  worked,but i have not test the other method.

**Comment by alpinegizmo** [comment]
Couldn't reproduce this with either openjdk version 1.7.0_141 or oracle java 1.7.0_79-b15, so this only affects some java 7 environments.

As Flink 1.4 is coming soon and will drop support for java 7, it's not worth fixing this now.
