### ISSUE TITLE
exercise link broken

### ISSUE THREAD

**Issue by bowenli86** [dataArtisans/flink-training-exercises#26]
The link of EventTimeJoinHelper.java in http://training.data-artisans.com/exercises/eventTimeJoin.html is broken. It should point to https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/java/com/dataartisans/flinktraining/exercises/datastream_java/process/EventTimeJoinHelper.java

**Comment by alpinegizmo** [comment]
Thanks; fixed.
